[package]
name = "nero"
version = "0.1.0"
authors = ["Rui Morais <ruipedromorais11@gmail.com>"]

[dependencies]
rand = "0.5.4"
byteorder = "1.2.3"
ring = "0.17.0-alpha.11"
hex = "0.3.2"
timer = "0.2.0"
chrono = "0.4.23"
